# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 10:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date', models.DateTimeField()),
                ('time', models.TimeField()),
                ('author', models.CharField(max_length=8)),
                ('readcount', models.IntegerField()),
                ('art', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_content', models.TextField()),
                ('date', models.DateTimeField()),
                ('commenttext', models.TextField()),
                ('commentname', models.CharField(max_length=8)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Article')),
            ],
        ),
        migrations.CreateModel(
            name='Flags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8, unique=True)),
                ('articlecount', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='flag',
            field=models.ManyToManyField(to='blog.Flags'),
        ),
    ]
