# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 01:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170924_0144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flags',
            old_name='articlecount',
            new_name='FlagId',
        ),
    ]
