# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 03:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170924_0158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flags',
            old_name='FlagId',
            new_name='flid',
        ),
        migrations.AlterField(
            model_name='article',
            name='flag',
            field=models.ManyToManyField(related_name='article', to='blog.Flags'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='com', to='blog.Article'),
        ),
    ]
