# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 04:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170924_0356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='time',
        ),
    ]
