# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_article_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='flag',
            field=models.ManyToManyField(related_name='flag_article', to='blog.Flags'),
        ),
    ]
